FROM python:3.11.13-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    libglib2.0-0 \
    libnss3 \
    libfontconfig1 \
    libx11-6 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxss1 \
    libxtst6 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libexpat1 \
    libgbm1 \
    libgdk-pixbuf-xlib-2.0-0 \
    libpango-1.0-0 \
    libasound2 \
    libatspi2.0-0 \
    libxshmfence1 \
    fonts-unifont \
    libxkbcommon0 \
    libcairo2 # Needed when running playwright in dev (UI mode) \ 
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements_dev.txt .
RUN pip install --no-cache-dir -r requirements_dev.txt
RUN playwright install chromium
COPY . .


# Expose port
EXPOSE 8000

# Run in reload mode for development
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
